---
name: CICD
on:
  workflow_dispatch: 
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo :Code Clone from github"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Builder docker container
        run: echo "Docker container build"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test the container
        run: echo "Testing the container"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying the app
        run: echo "Docker compose deployed the app"
