# This is workflow name
name: Hello 
# runs on trigger
on:
  push:
    branches: [main]
      
# These are jobs inside the workflow
jobs:

# This is name of job
  greet:
# github runner
    runs_on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "Hello Dosto"

      - name: say hello to username
        run: echo "Hello $USER"
